version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
 
platform: Any CPU
 
configuration: Release
 
build:
  publish_nuget: true
 
before_build:
  - nuget restore
 
deploy:
  provider: NuGet  
  api_key:
    secure: ueItpz8GrbP00/idHke1mVqPUxms1elvdVUhJRC8AV2JNtoEBF3znONhW+NPP2lG
  artifact: /.*\.nupkg/
