version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
 
platform: Any CPU
 
configuration: Release
 
build:
  verbosity: detailed
  publish_nuget: true
 
before_build:
  - nuget restore
 
deploy:
  provider: NuGet  
  api_key:
    secure: 4l4pCChWiZ3X+NYOQnbD3n5lCYyz8Gqo8PAuvDJ97cfTWruK+t7qzGHDHcDnHnia
  artifact: /.*\.nupkg/