version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
 
platform: Any CPU
 
configuration: Release

branches:
  only:
  - master
 
before_build:
  - nuget restore
 
 build:
  publish_nuget: true
 
deploy:
  provider: NuGet  
  api_key:
    secure: ueItpz8GrbP00/idHke1mVqPUxms1elvdVUhJRC8AV2JNtoEBF3znONhW+NPP2lG
  artifact: /.*\.nupkg/

artifacts:
  - path: 'testconsole\bin'
    name: bin

#deploy:
#  release: XASM-v$(appveyor_build_version)
#  provider: GitHub
#  auth_token:
#    secure: OCdVNN9IGRNgd0UfcMctZNVbKxMi4e3GneKo8+afU/iXCXhOxfrJ7PuysfxSDkq3
#  artifact: 'testconsole\bin'
#  draft: false
#  prerelease: false
#  on:
#    branch: master
